name: gestion_depenses
description: Une application Flutter de gestion des dépenses
publish_to: 'none' # Si vous ne publiez pas sur pub.dev

# Version minimale requise de Flutter
environment:
  sdk: ">=2.18.0 <3.0.0" # Assurez-vous de spécifier la bonne version de Dart

# Dépendances de l'application
dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15  # Exemple de dépendance pour la gestion de préférences partagées

# Dépendances de développement (pour les tests, etc.)
dev_dependencies:
  flutter_test:
    sdk: flutter

# Configuration des assets (par exemple pour des images, des icônes, etc.)
flutter:
  assets:
    - assets/images/  # Si vous avez un dossier 'images' pour les assets
